<?php
return [
    // Navigation
    'nav.back_to_dashboard' => 'กลับไปที่หน้าแรกของ Romar',
    'nav.section.primary' => 'เมนูหลัก',
    'nav.section.admin' => 'เมนูผู้ดูแลระบบ',
    'nav.section.support' => 'เมนูฝ่ายสนับสนุน',
    'nav.dashboard' => 'แดชบอร์ด',
'nav.tickets' => 'แจ้งปัญหา',
    'nav.assets' => 'ทรัพย์สิน',
    'nav.assets_categories' => 'หมวดหมู่ทรัพย์สิน',
    'nav.knowledgebase' => 'ฐานความรู้',
    'nav.users' => 'ผู้ใช้งาน',
    'nav.reports' => 'รายงาน',
    'nav.assets_reports' => 'รายงานทรัพย์สิน',
    'nav.sla' => 'ศูนย์ SLA',
    'nav.settings' => 'การตั้งค่า',
    'nav.logout' => 'ออกจากระบบ',

    // Maintenance
    'maintenance.page_title' => 'ซ่อมบำรุง',
    'maintenance.subtitle' => 'ระบบจัดการการซ่อมบำรุงทรัพย์สิน',
    'maintenance.stats.total_cost' => 'ค่าใช้จ่ายซ่อมทั้งหมด',
    'maintenance.stats.total_repairs' => 'รายการซ่อมทั้งหมด',
    'maintenance.stats.monthly_cost' => 'ค่าใช้จ่ายรายเดือน',
    'maintenance.stats.open_repairs' => 'ซ่อมค้าง',
    'maintenance.form.new_title' => 'บันทึกการซ่อมใหม่',
    'maintenance.form.asset' => 'ทรัพย์สิน',
    'maintenance.form.select_asset' => 'เลือกทรัพย์สิน',
    'maintenance.form.repair_date' => 'วันที่ซ่อม',
    'maintenance.form.problem' => 'ปัญหา',
    'maintenance.form.problem_placeholder' => 'อธิบายปัญหาที่พบ',
    'maintenance.form.status' => 'สถานะ',
    'maintenance.form.technician' => 'ช่างเทคนิค',
    'maintenance.form.vendor' => 'ผู้ขาย/ร้านค้า',
    'maintenance.form.cost' => 'ค่าใช้จ่าย',
    'maintenance.form.warranty_claim' => 'เคลมการรับประกัน',
    'maintenance.form.submit' => 'บันทึกการซ่อม',
    'maintenance.search.placeholder' => 'ค้นหา...',
    'maintenance.search.status' => 'สถานะ',
    'maintenance.search.date_from' => 'วันที่เริ่ม',
    'maintenance.search.date_to' => 'วันที่สิ้นสุด',
    'maintenance.search.filter_clear' => 'ล้างตัวกรอง',
    'maintenance.no_results' => 'ไม่พบข้อมูลการซ่อม',
    'maintenance.status.in_progress' => 'กำลังดำเนินการ',
    'maintenance.status.completed' => 'เสร็จสิ้น',
    'maintenance.status.pending' => 'รออะไหล่',
    'maintenance.confirm.delete' => 'ยืนยันการลบข้อมูลการซ่อมนี้',
    'maintenance.pagination.page' => 'หน้า %1$d จาก %2$d',

    // Page headings
    'page.title.dashboard' => 'แดชบอร์ดฝ่ายสนับสนุนไอที',
    'page.subtitle.dashboard' => 'ภาพรวม KPI การแจ้งเตือน และสุขภาพแพลตฟอร์ม',
'page.title.tickets' => 'แจ้งปัญหา',
    'page.title.assets' => 'ทรัพย์สิน',
    'page.title.knowledgebase' => 'ฐานความรู้',
    'page.subtitle.knowledgebase' => 'คู่มือและบทความที่ฝ่ายสนับสนุนไอทีดูแล',
    'page.title.reports' => 'รายงานตั๋ว',
    'page.title.settings' => 'การตั้งค่าระบบ',
    'page.subtitle.settings' => 'ปรับการแจ้งเตือน อีเมล และกฎ SLA ให้สอดคล้องกับนโยบาย',
    'page.title.assets_reports' => 'ข้อมูลเชิงลึกการซ่อมทรัพย์สิน',
    'page.subtitle.assets_reports' => 'ค่าใช้จ่ายการซ่อม การรับประกัน และค่าตัดจำหน่ายของทรัพย์สินสำคัญ',
    'page.title.users' => 'รายชื่อผู้ใช้งาน',
    'page.subtitle.users' => 'จัดการบัญชีพนักงาน ผู้ดูแล และฝ่ายสนับสนุนจากที่เดียว',
    'page.title.slaconfig' => 'การกำหนดค่า SLA',
    'page.subtitle.slaconfig' => 'กำหนดเป้าหมายการตอบสนองและการแก้ไขตามระดับ SLA',

    // Settings categories
    'settings.category.general' => 'ทั่วไป',
    'settings.category.email' => 'อีเมล',
    'settings.category.notifications' => 'การแจ้งเตือน',
    'settings.category.tickets' => 'ตั๋วสนับสนุน',

    // Settings
    'settings.updated' => 'อัปเดตการตั้งค่า %d รายการเรียบร้อยแล้ว',
    'settings.failed' => 'ไม่สามารถอัปเดตการตั้งค่าได้',
    'settings.csrf_error' => 'โทเค็น CSRF ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง',

    // Dashboard
    'dashboard.assets.section.title' => 'ทรัพย์สินไอที',
    'dashboard.assets.section.subtitle' => 'สรุปประเภทและจำนวนทรัพย์สิน',
    'dashboard.tickets.section.title' => 'ตั๋ว IT แยกตามหมวดหมู่',
    'dashboard.tickets.section.subtitle' => 'ดูแนวโน้มตั๋วตามประเภทปัญหา',
    'dashboard.recent.title' => 'ตั๋วล่าสุด',
    'dashboard.recent.subtitle' => 'ตั๋ว 10 รายการล่าสุดที่สร้างขึ้น',
    'dashboard.assets_status' => 'สถานะทรัพย์สิน',
    'dashboard.tickets_status' => 'สถานะตั๋ว',
    'dashboard.view_tickets_btn' => 'ดูตั๋วทั้งหมด',

    // Buttons
    'button.create_ticket' => 'แจ้งปัญหา',
    'button.create_article' => 'บทความใหม่',
    'button.export_excel' => 'ส่งออก Excel',
    'button.save_settings' => 'บันทึกการตั้งค่า',
    'button.search' => 'ค้นหา',
    'button.view_article' => 'ดูบทความ',
    'button.helpful' => 'มีประโยชน์',

    // Filters
    'filter.search_placeholder' => 'ค้นหาบทความ...',
    'filter.all_categories' => 'ทุกหมวดหมู่',
    'filter.label.start_date' => 'วันที่เริ่มต้น',
    'filter.label.end_date' => 'วันที่สิ้นสุด',
    'filter.label.report_type' => 'ประเภทการรายงาน',
    'assetsreports.filter.year_label' => 'ปี',
    'assetsreports.filter.month_label' => 'เดือน',
    'assetsreports.filter.apply' => 'ใช้ตัวกรอง',

    // Status & counts
    'status.total_articles' => 'บทความทั้งหมด',
    'status.total_views' => 'ยอดเข้าชม',
    'status.total_helpful' => 'คะแนนว่ามีประโยชน์',
    'status.total_tickets' => 'ตั๋วทั้งหมด',
    'status.new_tickets' => 'ตั๋วใหม่',
    'status.in_progress_tickets' => 'กำลังดำเนินการ',
    'status.resolved_tickets' => 'Resolved',
    'status.closed_tickets' => 'ปิดแล้ว',
    'status.overdue_tickets' => 'การละเมิด SLA',
    'status.avg_resolution_time' => 'เวลาเฉลี่ยในการแก้ไข (ชม.)',
    'status.high_priority' => 'ลำดับความสำคัญสูง',
    'status.urgent_priority' => 'ด่วน',

    // Widgets & empty states
    'widget.categories' => 'หมวดหมู่',
    'widget.popular_articles' => 'บทความยอดนิยม',
    'empty.knowledgebase.title' => 'ยังไม่มีบทความ',
    'empty.knowledgebase.body' => 'เผยแพร่บทความใหม่เพื่อแนะนำทีมงาน',
    'dashboard.assets.empty' => 'ยังไม่มีข้อมูลทรัพย์สิน',
    'dashboard.tickets.empty' => 'ยังไม่มีตั๋ว',
    'dashboard.notification.empty' => 'ไม่มีการแจ้งเตือนใหม่ใน 7 วันที่ผ่านมา',

    // Modals
    'modal.article_view_title' => 'อ่านบทความ',
    'modal.article_add_title' => 'สร้างบทความ',

    // Reports
    'reports.subtitle.summary' => 'ภาพรวม KPI บริการ',
    'reports.subtitle.category' => 'แยกตามหมวดหมู่',
    'reports.subtitle.priority' => 'ลำดับความสำคัญเทียบกับ SLA',
    'reports.subtitle.sla' => 'ติดตามการปฏิบัติตาม SLA',
    'reports.subtitle.default' => 'รายงานIT Tickets',
    'report_type.summary' => 'สรุป',
    'report_type.category' => 'หมวดหมู่',
    'report_type.priority' => 'ลำดับความสำคัญ',
    'report_type.sla' => 'การปฏิบัติตาม SLA',

    // Settings & system
    'settings.section_title' => 'หมวดหมู่การตั้งค่า',
    'settings.section_subtitle' => 'ปรับค่าเริ่มต้นอีเมล การแจ้งเตือน และ SLA ให้สอดคล้องกับนโยบาย Romar',

    // System
    'system.section_title' => 'ข้อมูลระบบ',
    'system.section_subtitle' => 'สุขภาพเซิร์ฟเวอร์ สภาพแวดล้อม และรายละเอียดการทำงาน',

    // Notifications & toasts
    'notification.header' => 'การแจ้งเตือน',
    'notification.mark_all' => 'การแจ้งเตือนทั้งหมดอ่านแล้ว',
    'time.just_now' => 'เมื่อสักครู่',
    'time.minutes_ago' => '%d นาทีที่แล้ว',
    'time.hours_ago' => '%d ชั่วโมงที่แล้ว',
    'time.days_ago' => '%d วันที่แล้ว',
    'toast.notifications_marked' => 'ทำเครื่องหมายการแจ้งเตือนทั้งหมดแล้ว',
    'toast.notifications_mark_error' => 'ไม่สามารถทำเครื่องหมายได้ กรุณาลองใหม่อีกครั้ง',
    'toast.server_unreachable' => 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ โปรดลองอีกครั้ง',

    // Asset reports
    'assetsreports.stats.total_cost' => 'ค่าใช้จ่ายซ่อม (YTD)',
    'assetsreports.stats.total_repairs' => 'รายการซ่อมที่บันทึก',
    'assetsreports.stats.warranty_claims' => 'เคลมการรับประกัน',
    'assetsreports.stats.borrowed_assets' => 'ทรัพย์สินที่ยืมไป',
    'assetsreports.charts.monthly' => 'ค่าใช้จ่ายซ่อมรายเดือน (%s)',
    'assetsreports.charts.by_type' => 'ค่าใช้จ่ายซ่อมตามประเภททรัพย์สิน',
    'assetsreports.section.top_assets' => 'ทรัพย์สินที่ซ่อมบ่อย',
    'assetsreports.section.all_repairs' => 'บันทึกการซ่อม',
    'assetsreports.section.depreciation' => 'ภาพรวมค่าตัดจำหน่าย',

    // Tickets
    'tickets.stats.total' => 'ตั๋วทั้งหมด',
    'tickets.stats.new' => 'ใหม่',
    'tickets.stats.in_progress' => 'กำลังดำเนินการ',
    'tickets.stats.resolved' => 'ตั๋วที่แก้ไขแล้ว',
    'tickets.stats.overdue' => 'SLA overdue',
    'tickets.filter.search_placeholder' => 'Search tickets...',
    'tickets.filter.status' => 'สถานะ',
    'tickets.filter.priority' => 'ลำดับความสำคัญ',
    'tickets.filter.category' => 'หมวดหมู่',
    'tickets.filter.assigned' => 'Assigned to',
    'tickets.filter.assigned_me' => 'My tickets',
    'tickets.filter.clear' => 'Clear filters',
    'tickets.status.new' => 'ใหม่',
    'tickets.status.assigned' => 'ถูกมอบหมาย',
    'tickets.status.in_progress' => 'กำลังดำเนินการ',
    'tickets.status.resolved' => 'Resolved',
    'tickets.status.closed' => 'ปิดแล้ว',
    'tickets.priority.low' => 'ต่ำ',
    'tickets.priority.normal' => 'ปกติ',
    'tickets.priority.high' => 'สูง',
    'tickets.priority.urgent' => 'ด่วน',
    'tickets.category.hardware' => 'ฮาร์ดแวร์',
    'tickets.category.software' => 'ซอฟต์แวร์',
    'tickets.category.network' => 'เครือข่าย',
    'tickets.category.account' => 'บัญชี',
    'tickets.category.other' => 'อื่น ๆ',
    'tickets.category.printer' => 'เครื่องพิมพ์',
    'tickets.category.email' => 'อีเมล',
    'tickets.empty.title' => 'ยังไม่มีการแจ้งปัญหาการใช้งาน IT',
    'tickets.empty.body' => '',
    'tickets.read_more' => 'อ่านเพิ่มเติม',
    'tickets.table.comments' => 'ความคิดเห็น',
    'tickets.table.hours' => 'ชม.',
    'tickets.sla.within' => 'อยู่ใน SLA',
    'tickets.sla.overdue' => 'เกินกำหนด %s ชั่วโมง',
    'tickets.sla.warning' => 'ใกล้ครบกำหนด (%s ชม. ที่เหลือ)',
    'tickets.sla.remaining' => '%s ชั่วโมงที่เหลือ',
    'tickets.sla.closed' => 'ปิดแล้ว',
    'tickets.form.create_title' => 'แจ้งปัญหา',
    'tickets.form.title' => 'หัวข้อ',
    'tickets.form.title_placeholder' => 'กรอกหัวข้อสั้น ๆ',
    'tickets.form.category' => 'หมวดหมู่ปัญหา',
    'tickets.form.category_placeholder' => 'เลือกหมวดหมู่',
    'tickets.form.asset' => 'ทรัพย์สินที่เกี่ยวข้อง',
    'tickets.form.asset_none' => 'ไม่มี',
    'tickets.form.urgency' => 'ความเร่งด่วน',
    'tickets.urgency.low' => 'ต่ำ - ผลกระทบน้อย',
    'tickets.urgency.medium' => 'ปานกลาง - ผลกระทบปานกลาง',
    'tickets.urgency.high' => 'สูง - มีผลกระทบต่อธุรกิจ',
    'tickets.urgency.critical' => 'วิกฤต - ระบบล่ม',
    'tickets.form.impact' => 'ผลกระทบ',
    'tickets.impact.low' => 'ต่ำ - ผู้ใช้รายบุคคล',
    'tickets.impact.medium' => 'ปานกลาง - กลุ่มผู้ใช้',
    'tickets.impact.high' => 'สูง - ระดับแผนก',
    'tickets.impact.critical' => 'วิกฤต - ทั้งองค์กร',
    'tickets.form.priority' => 'ลำดับความสำคัญ',
    'tickets.form.location' => 'ที่ตั้ง',
    'tickets.form.location_placeholder' => 'อาคาร / ชั้น / ห้อง',
    'tickets.form.description' => 'รายละเอียด',
    'tickets.form.description_placeholder' => 'อธิบายปัญหาให้ละเอียดที่สุดเท่าที่จะทำได้...',
    'tickets.form.attachments' => 'ไฟล์แนบ (ไม่บังคับ)',
    'tickets.form.attachments_help' => 'คลิกหรือวางไฟล์เพื่ออัปโหลด',
    'tickets.form.attachments_note' => 'รองรับ JPG, PNG, PDF, DOC, XLS (สูงสุด 10MB)',
    'tickets.form.submit' => 'แจ้งปัญหา',
    'tickets.form.cancel' => 'ยกเลิก',

    'assetsreports.section.filters' => 'ตัวกรอง',
    'assetsreports.section.filters.subtitle' => 'ปรับข้อมูลตามปีและเดือน',
    'assetsreports.table.top_assets.asset' => 'ทรัพย์สิน',
    'assetsreports.table.top_assets.type' => 'ประเภททรัพย์สิน',
    'assetsreports.table.top_assets.repairs' => 'จำนวนครั้งซ่อม',
    'assetsreports.table.top_assets.cost' => 'ยอดใช้จ่ายรวม',
    'assetsreports.table.repairs.date' => 'วันที่',
    'assetsreports.table.repairs.asset' => 'ทรัพย์สิน',
    'assetsreports.table.repairs.issue' => 'ปัญหา',
    'assetsreports.table.repairs.tech_vendor' => 'ช่าง / ผู้จัดหา',
    'assetsreports.table.repairs.cost' => 'ค่าใช้จ่าย',
    'assetsreports.table.repairs.warranty' => 'การรับประกัน',
    'assetsreports.table.repairs.status' => 'สถานะ',
    'assetsreports.table.depreciation.asset' => 'ทรัพย์สิน',
    'assetsreports.table.depreciation.purchase_price' => 'ราคาซื้อ',
    'assetsreports.table.depreciation.purchase_date' => 'วันที่ซื้อ',
    'assetsreports.table.depreciation.useful_life' => 'อายุใช้งาน (ปี)',
    'assetsreports.table.depreciation.annual' => 'ค่าตัดจำหน่ายรายปี',
    'assetsreports.table.depreciation.ytd' => 'ค่าตัดจำหน่ายสะสม',
    'assetsreports.table.depreciation.current_value' => 'มูลค่าปัจจุบัน',
    'assetsreports.table.depreciation.remaining' => 'คงเหลือ (%)',

    'slaconfig.section.title' => 'กฎ SLA',
    'slaconfig.section.subtitle' => 'ปรับเป้าหมายตอบสนองและแก้ไขตามคู่ลำดับความสำคัญและผลกระทบ',
    'slaconfig.label.response_time' => 'เวลาตอบสนอง (ชม.)',
    'slaconfig.label.resolution_time' => 'เวลาแก้ไข (ชม.)',
    'slaconfig.button.save_rule' => 'บันทึกกฎ SLA',
    'slaconconfig.message.csrf_error' => 'โทเค็น CSRF ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง',
    'slaconfig.message.updated' => 'ปรับปรุงกฎ SLA สำเร็จ',
    'slaconfig.message.failed' => 'ไม่สามารถปรับปรุงกฎ SLA ได้: {error}',
];
?>

