<?php
return [
    'assetsdetail.title' => 'Asset details',
    'assetsdetail.header.asset_name' => 'Asset name',
    'assetsdetail.header.asset_tag' => 'Asset tag',
    'assetsdetail.header.inventory_number' => 'Inventory number',
    'assetsdetail.section.device_info' => 'Device information',
    'assetsdetail.section.responsible' => 'Responsible party',
    'assetsdetail.section.os_hardware' => 'OS, hardware & network',
    'assetsdetail.section.purchase' => 'Purchase details',
    'assetsdetail.repair_history' => 'Repair history',
    'assetsdetail.borrow_history' => 'Borrow history',
    'assetsdetail.transfer_history' => 'Transfer history',
    'assetsdetail.depreciation' => 'Depreciation overview',
    'assetsdetail.add_repair' => 'Log repair',
    'assetsdetail.add_borrow' => 'Record borrow',
    'assetsdetail.add_transfer' => 'Record transfer',
    'assetsdetail.repair_saved' => 'Repair record saved successfully',
    'assetsdetail.borrow_saved' => 'Borrow record saved successfully',
    'assetsdetail.return_saved' => 'Return recorded successfully',
    'assetsdetail.transfer_saved' => 'Transfer recorded successfully',
    'assetsdetail.repair_date' => 'Repair date',
    'assetsdetail.repair_status' => 'Repair status',
    'assetsdetail.problem_desc' => 'Problem description',
    'assetsdetail.repair_detail' => 'Repair details',
    'assetsdetail.repair_cost' => 'Repair cost',
    'assetsdetail.vendor' => 'Vendor / service provider',
    'assetsdetail.technician' => 'Technician',
    'assetsdetail.warranty_claim' => 'Warranty claim',
    'assetsdetail.borrower' => 'Borrower',
    'assetsdetail.borrow_date' => 'Borrow date',
    'assetsdetail.expected_return' => 'Expected return',
    'assetsdetail.purpose' => 'Purpose',
    'assetsdetail.condition_out' => 'Condition at handover',
    'assetsdetail.active_borrow' => 'Active borrows',

    // Navigation overrides
    'nav.dashboard' => 'แดชบอร์ด',
    'nav.back_to_dashboard' => 'กลับไปยังแดชบอร์ด',
    'nav.assets' => 'ทรัพย์สิน',
    'nav.assets_categories' => 'หมวดหมู่ทรัพย์สิน',

    // Page titles
    'page.title.dashboard' => 'แดชบอร์ด',
    'page.subtitle.dashboard' => 'ติดตาม KPI และภาพรวมสถานะ IT ทั้งหมด',
    'page.title.assets' => 'ทรัพย์สิน IT',
    'page.subtitle.assets' => 'ระบบจัดการทรัพย์สินไอทีครบวงจร',
    'page.title.settings' => 'การตั้งค่าระบบ',
    'page.subtitle.settings' => 'จัดการอีเมล แจ้งเตือน และนโยบาย SLA',

    // Dashboard - Full coverage for ALL sections
    'dashboard.assets.section.title' => 'IT Assets ภาพรวม',
    'dashboard.assets.section.subtitle' => 'สรุปประเภท สถานะ และการใช้งานทรัพย์สิน IT ขององค์กร',
    'dashboard.tickets.section.title' => 'แจ้งปัญหาการใช้งาน IT แยกตามหมวดหมู่',
    'dashboard.tickets.section.subtitle' => 'สรุปตั๋วตามประเภทปัญหาและสถานะ SLA',
    'dashboard.assets.empty' => 'ยังไม่มีข้อมูลทรัพย์สินในระบบ',
    'dashboard.tickets.empty' => 'ยังไม่มีการแจ้งปัญหาการใช้งานในระบบ',
    'dashboard.assets_status' => 'สถานะทรัพย์สิน',
    'dashboard.tickets_status' => 'สถานะ Tickets',
    'dashboard.tickets_priority' => 'ตั๋วตามระดับความสำคัญ',
    'dashboard.top_brands' => 'แบรนด์ทรัพย์สินยอดนิยม',
    'dashboard.top_brands.title' => 'แบรนด์ทรัพย์สินยอดนิยม',
    'dashboard.recent_tickets_table' => 'ตั๋วล่าสุด',
    'dashboard.overdue_tickets' => 'ตั๋วเกิน SLA',
    'dashboard.warranty_expiring' => 'การรับประกันใกล้หมดอายุ 30 วัน',
    'dashboard.view_tickets_btn' => 'ดูตั๋วทั้งหมด',
    'dashboard.recent.title' => 'ตั๋วล่าสุด & กราฟสรุป',
    'dashboard.recent.subtitle' => 'ตั๋ว 30 วันล่าสุด + กราฟสรุปประสิทธิภาพ',
    'dashboard.alerts.title' => 'การแจ้งเตือน & คำเตือน',
    'dashboard.alerts.subtitle' => 'ตั๋วเกิน SLA + ทรัพย์สินหมดประกันใน 30 วัน',
    'dashboard.notification.empty' => 'ยังไม่มีแจ้งเตือนใหม่ใน 7 วัน',
    'dashboard.priority_chart.title' => 'ตั๋วตามระดับความสำคัญ',
    'dashboard.tickets.recent.card_title' => 'ตั๋วล่าสุด',
    'dashboard.ticket.created_by_label' => 'สร้างโดย',
    'dashboard.alerts.overdue.title' => 'ตั๋วเกิน SLA ({count} รายการ)',
    'dashboard.alerts.warranty.title' => 'ทรัพย์สินหมดประกัน ({count} รายการ)',

    // Time formatting (sprintf compatible)
    'time.hours_ago' => '%d ชั่วโมงที่แล้ว',
    'time.days_ago' => '%d วันที่แล้ว',
    'time.minutes_ago' => '%d นาทีที่แล้ว',
    'time.just_now' => 'เมื่อสักครู่',

    // Notifications (already partially there, enhanced)
    'notification.title' => 'การแจ้งเตือน',
    'notification.header' => 'การแจ้งเตือนล่าสุด',
    'notification.mark_all' => 'ทำเครื่องหมายอ่านทั้งหมด',
    'notification.empty' => 'ไม่มีแจ้งเตือนใหม่ใน 7 วัน',
    'notification.loading' => 'กำลังโหลดการแจ้งเตือน...',
    'toast.notifications_marked' => 'ทำเครื่องหมายแจ้งเตือนทั้งหมดแล้ว',
    'toast.notifications_mark_error' => 'เกิดข้อผิดพลาด กรุณาลองใหม่',
    'toast.server_unreachable' => 'ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้',

    // Settings (from garbled logActivity/category desc)
    'settings.category.general' => 'การตั้งค่าทั่วไป',
    'settings.category.general_desc' => 'การตั้งค่าเริ่มต้นของระบบและพารามิเตอร์ทั่วไป',
    'settings.category.email' => 'การตั้งค่า Email',
    'settings.category.email_desc' => 'การตั้งค่า SMTP และการส่งอีเมลแจ้งเตือนอัตโนมัติ',
    'settings.category.notifications' => 'การตั้งค่าแจ้งเตือน',
    'settings.category.notifications_desc' => 'กำหนดค่าการแจ้งเตือนและเวลาตอบสนอง SLA',
    'settings.category.tickets' => 'การตั้งค่า Tickets',
    'settings.category.tickets_desc' => 'กฎการจัดการตั๋ว IT และ workflow อัตโนมัติ',
    'settings.section_title' => 'การตั้งค่าหลักของระบบ',
    'settings.section_subtitle' => 'ปรับค่า SLA, อีเมล และแจ้งเตือนให้สอดคล้องกับนโยบายองค์กร',
    'settings.success_message' => 'บันทึกการตั้งค่าเรียบร้อย ({count} รายการ)',
    'settings.csrf_error' => 'โทเค็น CSRF ไม่ถูกต้อง กรุณาลองใหม่อีกครั้ง',
    'settings.updated' => 'ปรับปรุงกฎ SLA สำเร็จ',
    'settings.failed' => 'ไม่สามารถบันทึกการตั้งค่าได้ กรุณาลองใหม่อีกครั้ง',
    'button.add_asset' => 'Add new assets',
    'button.save_settings' => 'บันทึกการตั้งค่า',
    'system.section_title' => 'ข้อมูลระบบทั่วไป',
    'system.section_subtitle' => 'สถานะเซิร์ฟเวอร์และอินฟราสตรัคเจอร์ล่าสุด',
];
