<?php
return [
    // Navigation
    'nav.back_to_dashboard' => 'Back to Romar home',
    'nav.section.primary' => 'Primary menu',
    'nav.section.admin' => 'Admin menu',
    'nav.section.support' => 'Support menu',
    'nav.dashboard' => 'Dashboard',
    'nav.tickets' => 'IT Tickets',
    'nav.assets' => 'Assets',
    'nav.assets_categories' => 'Asset categories',
    'nav.knowledgebase' => 'Knowledge base',
    'nav.users' => 'Users',
    'nav.reports' => 'Reports',
    'nav.assets_reports' => 'Asset reports',
    'nav.sla' => 'SLA center',
    'nav.settings' => 'Settings',
    'nav.logout' => 'Sign out',

    // Page headings
    'page.title.dashboard' => 'IT Support Dashboard',
    'page.subtitle.dashboard' => 'Executive overview of KPI, alerts, and platform health',
    'page.title.tickets' => 'IT Tickets',
    'page.title.assets' => 'Assets',
    'page.title.knowledgebase' => 'Knowledge Base',
    'page.subtitle.knowledgebase' => 'Curated guides and articles maintained by IT Support',
    'page.title.reports' => 'Ticket Reports',
    'page.title.settings' => 'System Settings',
    'page.subtitle.settings' => 'Align notifications, email, and SLA rules with policy',
    'page.title.assets_reports' => 'Asset Repair Insights',
    'page.subtitle.assets_reports' => 'Repair spend, warranties, and depreciation data for key assets',
    'page.title.users' => 'User Directory',
    'page.subtitle.users' => 'Manage staff, admin, and support accounts from one place',
    'page.title.slaconfig' => 'SLA Configuration',
    'page.subtitle.slaconfig' => 'Define response and resolution goals for each SLA tier',

    // Buttons
    'button.create_ticket' => 'Create ticket',
    'button.create_article' => 'New article',
    'button.export_excel' => 'Export Excel',
    'button.save_settings' => 'Save settings',
    'button.search' => 'Search',
    'button.view_article' => 'View article',
    'button.helpful' => 'Helpful',

    // Filters
    'filter.search_placeholder' => 'Search articles...',
    'filter.all_categories' => 'All categories',
    'filter.label.start_date' => 'Start date',
    'filter.label.end_date' => 'End date',
    'filter.label.report_type' => 'Report type',
    'assetsreports.filter.year_label' => 'Year',
    'assetsreports.filter.month_label' => 'Month',
    'assetsreports.filter.apply' => 'Apply filter',

    // Status & counts
    'status.total_articles' => 'Total articles',
    'status.total_views' => 'Total views',
    'status.total_helpful' => 'Helpfulness votes',
    'status.total_tickets' => 'Total tickets',
    'status.new_tickets' => 'New tickets',
    'status.in_progress_tickets' => 'In progress',
    'status.resolved_tickets' => 'Resolved',
    'status.closed_tickets' => 'Closed',
    'status.overdue_tickets' => 'SLA breaches',
    'status.avg_resolution_time' => 'Average resolution (hrs)',
    'status.high_priority' => 'High priority',
    'status.urgent_priority' => 'Urgent',

    // Widgets & empty states
    'widget.categories' => 'Categories',
    'widget.popular_articles' => 'Popular articles',
    'empty.knowledgebase.title' => 'No articles yet',
    'empty.knowledgebase.body' => 'Publish a new article to guide the team',

    // Modals
    'modal.article_view_title' => 'Read article',
    'modal.article_add_title' => 'Create article',

    // Reports
    'reports.subtitle.summary' => 'Service KPI overview',
    'reports.subtitle.category' => 'Breakdown by category',
    'reports.subtitle.priority' => 'Priority vs. SLA',
    'reports.subtitle.sla' => 'SLA compliance monitoring',
    'reports.subtitle.default' => 'IT ticket reporting',
    'report_type.summary' => 'Summary',
    'report_type.category' => 'Category',
    'report_type.priority' => 'Priority',
    'report_type.sla' => 'SLA compliance',

    // Settings & system
    'settings.section_title' => 'Setting categories',
    'settings.section_subtitle' => 'Adjust email, notification, and SLA defaults to match policy',
    'system.section_title' => 'System information',
    'system.section_subtitle' => 'Server health, environment, and runtime details',

    // Notifications & toasts
    'notification.title' => 'Notifications',
    'notification.mark_all' => 'Mark all as read',
    'notification.empty' => 'No new notifications in the last 7 days',
    'toast.notifications_marked' => 'All notifications marked read',
    'toast.notifications_mark_error' => 'Unable to mark notifications, please retry',
    'toast.server_unreachable' => 'Cannot reach the server, please try again',

    // Asset reports
    'assetsreports.stats.total_cost' => 'Repair spend (YTD)',
    'assetsreports.stats.total_repairs' => 'Repairs recorded',
    'assetsreports.stats.warranty_claims' => 'Warranty claims',
    'assetsreports.stats.borrowed_assets' => 'Assets borrowed',
    'assetsreports.charts.monthly' => 'Monthly repair spend (%s)',
    'assetsreports.charts.by_type' => 'Repair spend by asset type',
    'assetsreports.section.top_assets' => 'Top repaired assets',
    'assetsreports.section.all_repairs' => 'Repair log',
    'assetsreports.section.depreciation' => 'Depreciation snapshot',
    // Tickets
    'tickets.stats.total' => 'Total tickets',
    'tickets.stats.new' => 'New',
    'tickets.stats.in_progress' => 'In progress',
    'tickets.stats.resolved' => 'Resolved tickets',
    'tickets.stats.overdue' => 'SLA overdue',
    'tickets.filter.search_placeholder' => 'Search tickets...',
    'tickets.filter.status' => 'Status',
    'tickets.filter.priority' => 'Priority',
    'tickets.filter.category' => 'Category',
    'tickets.filter.assigned' => 'Assigned to',
    'tickets.filter.assigned_me' => 'My tickets',
    'tickets.filter.clear' => 'Clear filters',
    'tickets.status.new' => 'New',
    'tickets.status.assigned' => 'Assigned',
    'tickets.status.in_progress' => 'In progress',
    'tickets.status.resolved' => 'Resolved',
    'tickets.status.closed' => 'Closed',
    'tickets.priority.low' => 'Low',
    'tickets.priority.normal' => 'Normal',
    'tickets.priority.high' => 'High',
    'tickets.priority.urgent' => 'Urgent',
    'tickets.category.hardware' => 'Hardware',
    'tickets.category.software' => 'Software',
    'tickets.category.network' => 'Network',
    'tickets.category.account' => 'Account',
    'tickets.category.other' => 'Other',
    'tickets.category.printer' => 'Printer',
    'tickets.category.email' => 'Email',
    'tickets.empty.title' => 'No tickets yet',
    'tickets.empty.body' => 'Create a ticket to populate this view',
    'tickets.read_more' => 'Read more',
    'tickets.table.comments' => 'comments',
    'tickets.table.hours' => 'hrs',
    'tickets.sla.within' => 'Within SLA',
    'tickets.sla.overdue' => 'Overdue by %s hours',
    'tickets.sla.warning' => 'Approaching deadline (%s hrs left)',
    'tickets.sla.remaining' => '%s hours remaining',
    'tickets.sla.closed' => 'Closed',
    'tickets.form.create_title' => 'Create new ticket',
    'tickets.form.title' => 'Title',
    'tickets.form.title_placeholder' => 'Brief subject line',
    'tickets.form.category' => 'Issue category',
    'tickets.form.category_placeholder' => 'Select category',
    'tickets.form.asset' => 'Related asset',
    'tickets.form.asset_none' => 'None',
    'tickets.form.urgency' => 'Urgency',
    'tickets.urgency.low' => 'Low - Minimal impact',
    'tickets.urgency.medium' => 'Medium - Moderate impact',
    'tickets.urgency.high' => 'High - Business impact',
    'tickets.urgency.critical' => 'Critical - Operational outage',
    'tickets.form.impact' => 'Impact',
    'tickets.impact.low' => 'Low - Individual user',
    'tickets.impact.medium' => 'Medium - Group of users',
    'tickets.impact.high' => 'High - Department-level',
    'tickets.impact.critical' => 'Critical - Organization-wide',
    'tickets.form.priority' => 'Priority',
    'tickets.form.location' => 'Location',
    'tickets.form.location_placeholder' => 'Building / Floor / Room',
    'tickets.form.description' => 'Description',
    'tickets.form.description_placeholder' => 'Describe the issue with as much detail as possible...',
    'tickets.form.attachments' => 'Attachments (optional)',
    'tickets.form.attachments_help' => 'Click or drag files to upload',
    'tickets.form.attachments_note' => 'Supported formats: JPG, PNG, PDF, DOC, XLS (max 10MB)',
    'tickets.form.submit' => 'Create ticket',
    'tickets.form.cancel' => 'Cancel',
    'assetsreports.section.filters' => 'Filters',
    'assetsreports.section.filters.subtitle' => 'Refine the data by year and month',
    'assetsreports.table.top_assets.asset' => 'Asset',
    'assetsreports.table.top_assets.type' => 'Asset type',
    'assetsreports.table.top_assets.repairs' => 'Repairs',
    'assetsreports.table.top_assets.cost' => 'Total spend',
    'assetsreports.table.repairs.date' => 'Date',
    'assetsreports.table.repairs.asset' => 'Asset',
    'assetsreports.table.repairs.issue' => 'Issue',
    'assetsreports.table.repairs.tech_vendor' => 'Tech / Vendor',
    'assetsreports.table.repairs.cost' => 'Cost',
    'assetsreports.table.repairs.warranty' => 'Warranty',
    'assetsreports.table.repairs.status' => 'Status',
    'assetsreports.table.depreciation.asset' => 'Asset',
    'assetsreports.table.depreciation.purchase_price' => 'Purchase price',
    'assetsreports.table.depreciation.purchase_date' => 'Purchase date',
    'assetsreports.table.depreciation.useful_life' => 'Useful life (yrs)',
    'assetsreports.table.depreciation.annual' => 'Annual depreciation',
    'assetsreports.table.depreciation.ytd' => 'YTD depreciation',
    'assetsreports.table.depreciation.current_value' => 'Current value',
    'assetsreports.table.depreciation.remaining' => 'Remaining (%)',
    'slaconfig.section.title' => 'SLA rules',
    'slaconfig.section.subtitle' => 'Adjust response and resolution goals per priority-impact pair',
    'slaconfig.label.response_time' => 'Response time (hours)',
    'slaconfig.label.resolution_time' => 'Resolution time (hours)',
    'slaconfig.button.save_rule' => 'Save SLA rule',
    'slaconfig.message.csrf_error' => 'Invalid CSRF token. Please try again.',
    'slaconfig.message.updated' => 'SLA rule updated successfully.',
    'slaconfig.message.failed' => 'Unable to update SLA rule: {error}',
];
