<?php
return [
    'assetsdetail.title' => 'Asset details',
    'assetsdetail.header.asset_name' => 'Asset name',
    'assetsdetail.header.asset_tag' => 'Asset tag',
    'assetsdetail.header.inventory_number' => 'Inventory number',
    'assetsdetail.section.device_info' => 'Device information',
    'assetsdetail.section.responsible' => 'Responsible party',
    'assetsdetail.section.os_hardware' => 'OS, hardware & network',
    'assetsdetail.section.purchase' => 'Purchase details',
    'assetsdetail.repair_history' => 'Repair history',
    'assetsdetail.borrow_history' => 'Borrow history',
    'assetsdetail.transfer_history' => 'Transfer history',
    'assetsdetail.depreciation' => 'Depreciation overview',
    'assetsdetail.add_repair' => 'Log repair',
    'assetsdetail.add_borrow' => 'Record borrow',
    'assetsdetail.add_transfer' => 'Record transfer',
    'assetsdetail.repair_saved' => 'Repair record saved successfully',
    'assetsdetail.borrow_saved' => 'Borrow record saved successfully',
    'assetsdetail.return_saved' => 'Return recorded successfully',
    'assetsdetail.transfer_saved' => 'Transfer recorded successfully',
    'assetsdetail.repair_date' => 'Repair date',
    'assetsdetail.repair_status' => 'Repair status',
    'assetsdetail.problem_desc' => 'Problem description',
    'assetsdetail.repair_detail' => 'Repair details',
    'assetsdetail.repair_cost' => 'Repair cost',
    'assetsdetail.vendor' => 'Vendor / service provider',
    'assetsdetail.technician' => 'Technician',
    'assetsdetail.warranty_claim' => 'Warranty claim',
    'assetsdetail.borrower' => 'Borrower',
    'assetsdetail.borrow_date' => 'Borrow date',
    'assetsdetail.expected_return' => 'Expected return',
    'assetsdetail.purpose' => 'Purpose',
    'assetsdetail.condition_out' => 'Condition at handover',
    'assetsdetail.active_borrow' => 'Active borrows',
];
